### ISSUE TITLE
Cannot be activated at localhost

### ISSUE THREAD

**Issue by wesandradealves** [pimedia/json-api-user#12]
Does someone knows how could I get it bypassed? Im trying activate my license at my localhost instance but with no success... :'(

**Comment by pimedia** [comment]
Please re-download version 3.7.2 from the purchase link.
It will allow localhost.

    On Wednesday, November 10, 2021, 08:02:41 AM GMT+5, Wesley Andrade (WES) ***@***.***> wrote:  
 
 


Does someone knows how could I get it bypassed? Im trying activate my license at my localhost instance but with no success... :'(

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
